query getDiscussions($id: ID!, $cursor: String) {
    node(id: $id) {
        ... on Discussion {
            comments(first: 50, after: $cursor) {
                edges {
                    node {
                        id
                        databaseId
                        isAnswer
                        publishedAt
                        createdAt
                        author {
                            login
                            url
                        }
                        bodyHTML
                        replies {
                            totalCount
                        }
                    }
                }
                pageInfo {
                    # startCursor
                    endCursor
                    hasNextPage
                }
            }
        }
    }
}
